# Generated by Django 5.1.15 on 2026-10-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('businesses', '0001_initial'),
        ('villas', '0004_partition_rent_partition_partition_rent_non_negative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_assignment',
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', False)), fields=('user', 'role', 'business'), name='unique_business_assignment'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('villa__isnull', False)), fields=('user', 'role', 'villa'), name='unique_villa_assignment'),
        ),
    ]
