# Generated by Django 5.1.15 on 2026-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_assignment_unique_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='can_add_partitions',
            field=models.BooleanField(default=False),
        ),
    ]
