# Generated by Django 5.1.15 on 2026-10-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_per_partition_per_period',
        ),
    ]
