import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [('villas', '0002_partition'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [migrations.CreateModel(name='Tenant', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=200)), ('mobile', models.CharField(blank=True, max_length=32)), ('id_document_number', models.CharField(blank=True, max_length=64)), ('nationality', models.CharField(blank=True, max_length=100)), ('move_in_date', models.DateField()), ('move_out_date', models.DateField(blank=True, null=True)), ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)), ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)), ('status', models.CharField(choices=[('active', 'Active'), ('moved_out', 'Moved Out'), ('archived', 'Archived')], default='active', max_length=20)), ('notes', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)), ('partition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='villas.partition')), ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-move_in_date'], 'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('partition',), name='unique_active_tenant_per_partition'), models.CheckConstraint(condition=models.Q(('monthly_rent__gte', 0), ('deposit__gte', 0)), name='tenant_amounts_non_negative')]})]
