# Generated by Django 5.1.15 on 2026-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login", "Login"),
                    ("auth.logout", "Logout"),
                    ("auth.failed_login", "Failed login"),
                    ("auth.password_changed", "Password changed"),
                    ("user.created", "User created"),
                    ("user.updated", "User updated"),
                    ("user.disabled", "User disabled"),
                    ("user.role_changed", "Role changed"),
                    ("user.business_assignment_changed", "Business assignment changed"),
                    ("user.villa_assignment_changed", "Villa assignment changed"),
                    ("business.created", "Business created"),
                    ("business.updated", "Business updated"),
                    ("business.archived", "Business archived"),
                    ("villa.created", "Villa created"),
                    ("villa.updated", "Villa updated"),
                    ("villa.archived", "Villa archived"),
                    ("partition.created", "Partition created"),
                    ("partition.updated", "Partition updated"),
                    ("partition.archived", "Partition archived"),
                    ("tenant.created", "Tenant created"),
                    ("tenant.updated", "Tenant updated"),
                    ("tenant.moved_in", "Tenant moved in"),
                    ("tenant.moved_out", "Tenant moved out"),
                    ("charge.created", "Charge created"),
                    ("charge.updated", "Charge updated"),
                    ("charge.cancelled", "Charge cancelled"),
                    ("invoice.created", "Invoice created"),
                    ("invoice.updated", "Invoice updated"),
                    ("invoice.cancelled", "Invoice cancelled"),
                    ("collection.created", "Collection created"),
                    ("collection.updated", "Collection updated"),
                    ("collection.cancelled", "Collection cancelled"),
                    ("expense.created", "Expense created"),
                    ("expense.updated", "Expense updated"),
                    ("expense.cancelled", "Expense cancelled"),
                    ("cash_handover.created", "Cash handover created"),
                    ("cash_handover.submitted", "Cash handover submitted"),
                    ("cash_handover.confirmed", "Cash handover confirmed"),
                    ("cash_handover.rejected", "Cash handover rejected"),
                    ("report.viewed", "Report viewed"),
                    ("report.exported", "Report exported"),
                    ("document.uploaded", "Document uploaded"),
                    ("document.downloaded", "Document downloaded"),
                    ("document.deleted", "Document deleted"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
