# Generated by Django 5.1.15 on 2026-10-02 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0003_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='partition',
            constraint=models.CheckConstraint(condition=models.Q(('rent__gte', 0), ('rent__isnull', True), _connector='OR'), name='partition_rent_non_negative'),
        ),
    ]
