# Generated by Django 5.1.15 on 2026-09-30 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("expenses", "0001_initial"),
        ("villas", "0002_partition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("paid_on__isnull", True),
                    models.Q(("payment_method", ""), _negated=True),
                    _connector="OR",
                ),
                name="expense_paid_has_method",
            ),
        ),
    ]
