# Generated by Django 5.1.15 on 2026-09-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("expenses", "0003_mark_existing_expenses_paid"),
        ("villas", "0003_photos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="paid_by",
            field=models.CharField(
                choices=[
                    ("staff", "Staff — from collected cash"),
                    ("owner", "Owner — own account"),
                ],
                default="owner",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="period",
            field=models.DateField(
                blank=True,
                help_text="First day of the month a recurring expense belongs to.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Day of the month it falls due (1–28)."
                    ),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("staff", "Staff — from collected cash"),
                            ("owner", "Owner — own account"),
                        ],
                        default="owner",
                        max_length=10,
                    ),
                ),
                (
                    "auto_debit",
                    models.BooleanField(
                        default=False,
                        help_text="Debited automatically from the owner account on the due date.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_expenses",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "villa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_expenses",
                        to="villas.villa",
                    ),
                ),
            ],
            options={
                "ordering": ["villa__name", "category__name"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="recurring",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="expenses.recurringexpense",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recurring__isnull", False)),
                fields=("recurring", "period"),
                name="one_expense_per_recurring_per_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recurring__isnull", True),
                    ("period__isnull", False),
                    _connector="OR",
                ),
                name="recurring_expense_has_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.UniqueConstraint(
                fields=("villa", "category"),
                name="unique_recurring_expense_per_villa_and_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="recurring_expense_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_day__gte", 1), ("due_day__lte", 28)),
                name="recurring_expense_due_day_1_to_28",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_debit", False), ("paid_by", "owner"), _connector="OR"
                ),
                name="recurring_auto_debit_is_owner_paid",
            ),
        ),
    ]
