# Generated by Django 5.1.15 on 2026-10-01 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("expenses", "0004_recurring_and_paid_by"),
        ("villas", "0003_photos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Owner / Business Manager confirmed the payment as received/valid.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verified_at__isnull", True),
                    ("paid_on__isnull", False),
                    _connector="OR",
                ),
                name="expense_verified_only_when_paid",
            ),
        ),
    ]
