# Generated by Django 5.1.15 on 2026-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0001_initial"),
        ("expenses", "0004_recurring_and_paid_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashhandover",
            name="expenses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Expenses the staff paid out of the collected cash; they reduce what is handed over.",
                related_name="handovers",
                to="expenses.expense",
            ),
        ),
    ]
