# Generated by Django 5.1.15 on 2026-09-30 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("expense_due_soon", "Expense due soon"),
                            ("expense_overdue", "Expense overdue"),
                            ("invoice_overdue", "Invoice overdue"),
                            ("cash_handover_pending", "Cash handover pending"),
                            ("cash_handover_rejected", "Cash handover rejected"),
                            ("contract_expiring", "Contract expiring"),
                            ("vacant_partition", "Vacant partition"),
                            ("collection_recorded", "Collection recorded"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, max_length=300)),
                ("url", models.CharField(max_length=300)),
                ("dedupe_key", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "resolved_at"],
                        name="notificatio_recipie_c09fee_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "dedupe_key"),
                        name="unique_notification_per_recipient_event",
                    )
                ],
            },
        ),
    ]
