# Generated by Django 5.1.15 on 2026-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("expense_due_soon", "Expense due soon"),
                    ("expense_overdue", "Expense overdue"),
                    ("expense_to_verify", "Expense awaiting verification"),
                    ("invoice_overdue", "Invoice overdue"),
                    ("cash_handover_pending", "Cash handover pending"),
                    ("cash_handover_rejected", "Cash handover rejected"),
                    ("contract_expiring", "Contract expiring"),
                    ("vacant_partition", "Vacant partition"),
                    ("collection_recorded", "Collection recorded"),
                ],
                max_length=40,
            ),
        ),
    ]
